// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StellarMinds.LogicaAccesoDatos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260422175806_agregarPrestamos")]
    partial class agregarPrestamos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEquipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");

                    b.HasDiscriminator<string>("TipoEquipo").HasValue("Equipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonturaId")
                        .HasColumnType("int");

                    b.Property<int>("TelescopioId")
                        .HasColumnType("int");

                    b.Property<int?>("VisualId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonturaId");

                    b.HasIndex("TelescopioId");

                    b.HasIndex("VisualId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Montura", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipo");

                    b.Property<bool>("Goto")
                        .HasColumnType("bit");

                    b.Property<int>("PesoMaximo")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Montura");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Telescopio", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipo");

                    b.Property<decimal>("Apertura")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("DistanciaFocal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<decimal>("RelacionFocal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasDiscriminator().HasValue("Telescopio");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Visual", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipo");

                    b.HasDiscriminator().HasValue("Visual");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Camara", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Visual");

                    b.Property<decimal>("PixelSize")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Resolucion")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Sensor")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Camara");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Ocular", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Visual");

                    b.Property<decimal>("AnguloVisual")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Diametro")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasDiscriminator().HasValue("Ocular");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Prestamo", b =>
                {
                    b.HasOne("StellarMinds.LogicaNegocio.Entidades.Montura", "Montura")
                        .WithMany()
                        .HasForeignKey("MonturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StellarMinds.LogicaNegocio.Entidades.Telescopio", "Telescopio")
                        .WithMany()
                        .HasForeignKey("TelescopioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StellarMinds.LogicaNegocio.Entidades.Visual", "Visual")
                        .WithMany()
                        .HasForeignKey("VisualId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("StellarMinds.LogicaNegocio.ValueObjects.VOPrestamo.FechaVO", "Fecha", b1 =>
                        {
                            b1.Property<int>("PrestamoId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Fin")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("Inicio")
                                .HasColumnType("datetime2");

                            b1.HasKey("PrestamoId");

                            b1.ToTable("Prestamos");

                            b1.WithOwner()
                                .HasForeignKey("PrestamoId");
                        });

                    b.Navigation("Fecha")
                        .IsRequired();

                    b.Navigation("Montura");

                    b.Navigation("Telescopio");

                    b.Navigation("Visual");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.OwnsOne("StellarMinds.LogicaNegocio.ValueObjects.VOUsuario.DireccionVO", "Direccion", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Calle1")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Calle2")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("StellarMinds.LogicaNegocio.ValueObjects.VOUsuario.NombreCompletoVO", "NombreCompleto", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Direccion")
                        .IsRequired();

                    b.Navigation("NombreCompleto")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
