// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StellarMinds.LogicaAccesoDatos;

#nullable disable

namespace StellarMinds.LogicaAccesoDatos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260421024903_AgregaEquipos2")]
    partial class AgregaEquipos2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEquipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");

                    b.HasDiscriminator<string>("TipoEquipo").HasValue("Equipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Direccion", "StellarMinds.LogicaNegocio.Entidades.Usuario.Direccion#DireccionVO", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Calle1")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Calle2")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NombreCompleto", "StellarMinds.LogicaNegocio.Entidades.Usuario.NombreCompleto#NombreCompletoVO", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Camara", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipo");

                    b.Property<decimal>("PixelSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Resolucion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sensor")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Camara");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Montura", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipo");

                    b.Property<bool>("Goto")
                        .HasColumnType("bit");

                    b.Property<int>("PesoMaximo")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Montura");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Ocular", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipo");

                    b.Property<decimal>("AnguloVisual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Diametro")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Ocular");
                });

            modelBuilder.Entity("StellarMinds.LogicaNegocio.Entidades.Telescopio", b =>
                {
                    b.HasBaseType("StellarMinds.LogicaNegocio.Entidades.Equipo");

                    b.Property<decimal>("Apertura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DistanciaFocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<decimal>("RelacionFocal")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Telescopio");
                });
#pragma warning restore 612, 618
        }
    }
}
